### ISSUE TITLE
WHAT IS DATA DIRECTORY?

### ISSUE THREAD

**Issue by manvirvirk** [zhuofeng/SR-cycleGAN#1]

**Comment by zhuofeng** [comment]
Sorry for replying so late. Could you point out DATA DIRECTORY is in which file?
By the way, this program can only read nifti file(a format of medical image)

**Comment by manvirvirk** [comment]
Thanks for reply, DATA DIRECTORY to load database for training and testing purpose.

**Comment by zhuofeng** [comment]
I got it. For loading training data, you have to edit train_options.py, and you will find:
parser.add_argument('--all_clinical_paths', type=str, default=[ 
                                                                         ], help='all clinical paths')
then you just need to edit the paths inside it like:
parser.add_argument('--all_clinical_paths', type=str, default=['filepath1',
                                                                                                  'filepath2'
                                                                         ], help='all clinical paths')
another is:
parser.add_argument('--all_micro_paths', type=str, default=[                     
], help='all micro paths')
you need to edit the paths inside it like:
parser.add_argument('--all_micro_paths', type=str, default=['filepath1',
                                                                                                  'filepath2'              
], help='all micro paths')

Note that our code needs CT and micro CT data for training. You also have to prepare the data.

**Comment by zhuofeng** [comment]
For testing, because we have some data that are private, we will write another python file for test soon in the future.
